version: '3'

services:
  kafka:
    image: docker.io/wurstmeister/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS="first_topic:1:1"
    networks:
      - trade-network
    depends_on:
      - zookeeper
  zookeeper:
    image: docker.io/wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper1
    volumes:
      - ./zookeeper_data:/var/lib/zookeeper/data:Z
    networks:
      - trade-network

networks:
  trade-network:
    external: true
    name: trade-network